version: '3.8'

services:
    app:
        container_name: twitch-dev-server
        env_file:
            - .env
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: development
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./src:/usr/src/app/src
            - ./tsconfig.json:/usr/src/app/tsconfig.json
        external_links:
            - mongo
        environment:
            - NODE_ENV=development
        command: npm run dev

    prod-app:
        container_name: twitch-prod-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        env_file:
            - .env
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./src:/usr/src/app/src
            - ./tsconfig.json:/usr/src/app/tsconfig.json
        external_links:
            - mongo
        environment:
            - NODE_ENV=production
        command: npm run start

    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - '27012:27017'

    nginx:
        image: reverse-proxy
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.nginx
        container_name: ${NGINX_HOST}
        env_file: .env
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
