version: '2'

services:
    app:
        container_name: twitch-dev-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: development
        env_file:
            - src/configs/env/.env
        ports:
            - '5000:5000'
        volumes:
            - ./src:/usr/src/app/src
            - ./tsconfig.json:/usr/src/app/tsconfig.json
        external_links:
            - mongo
        environment:
            - NODE_ENV=development
            - PORT=5000
            - DB_URI=${DB_URI}
        command: npm run dev

    prod-app:
        container_name: twitch-prod-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        env_file:
            - src/configs/env/.env
        ports:
            - '5001:5000'
        volumes:
            - ./src:/usr/src/app/src
            - ./tsconfig.json:/usr/src/app/tsconfig.json
        external_links:
            - mongo
            - DB_URI=${DB_URI}
        environment:
            - NODE_ENV=production
        command: npm run start

    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - '27017:27017'
