FROM node:20.11.1 as development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

WORKDIR /usr/src/app

COPY . . 

RUN npm install && npm cache clean --force

RUN npm run ts-prepare

CMD ["npx", "nodemon", "src/index.ts"]