FROM node:20.11.1 as development

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .
COPY src/configs/env/.env src/configs/env/.env

RUN npm install && npm cache clean --force

RUN npm run ts-prepare

CMD ["npx", "nodemon", "src/index.ts"]