version: '2'

services:
    app:
        container_name: twitch-dev-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: development
        env_file:
            - src/configs/env/.env
        ports:
            - '5000:5000'
        volumes:
            - ./src:/usr/src/app/src
            - ./tsconfig.json:/usr/src/app/tsconfig.json
        depends_on:
            - mongodb
        command: npm run dev

    prod-app:
        container_name: twitch-prod-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        env_file:
            - src/configs/env/.env
        ports:
            - '5001:5000'
        volumes:
            - ./src:/usr/src/app/src
            - ./tsconfig.json:/usr/src/app/tsconfig.json
        links:
            - mongodb
        command: npm run start

    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - '27012:27017'
